Added -o option to run_results
At the same time:
- reworked message levels;
- added a possible third argument to sixdeskmess, wich a command to
  be executed in case the message level is higher than the level requested
  by the user;

diff --git a/utilities/bash/run_results b/utilities/bash/run_results
--- a/utilities/bash/run_results
+++ b/utilities/bash/run_results
@@ -13,6 +13,10 @@ function how_to_use() {
    -B      break backward-compatibility
            for the moment, this sticks only to job names
    -t      reprocess old archives of trashed WUs already parsed
+   -o      define output (preferred over the definition of sixdesklevel in sixdeskenv)
+               0: only error messages and basic output 
+               1: full output
+               2: extended output for debugging
 
 EOF
 }
@@ -325,7 +329,7 @@ function downloadNewResults(){
 	unknown="false"
 	
 #MACRO mymess 1 Now treating TaskID $taskid
-	sixdeskmess 1 "Now treating TaskID $taskid"
+	sixdeskmess -1 "Now treating TaskID $taskid"
 #MACRO mymess
 	
 	Runnam=""
@@ -461,7 +465,7 @@ function downloadNewResults(){
 			
 			anerror="true"
 		    else
-			echo "Found in hierarchy $sixdeskboincdir"
+			sixdeskmess 1 "Found in hierarchy $sixdeskboincdir"
 			found="true"
 		    fi
 		    if test "$found" = "true"
@@ -1008,7 +1012,7 @@ function downloadNewResults(){
 	then
 	    
 #MACRO mymess 1 Saving fort.10.gz and updating completed jobs etc
-	    sixdeskmess -1 "Saving fort.10.gz and updating completed jobs etc"
+	    sixdeskmess 1 "Saving fort.10.gz and updating completed jobs etc"
 #MACRO mymess
 	    
 	    if test "$duplicate" = "false"
@@ -1141,7 +1145,7 @@ function downloadNewResults(){
 	    
 	    
 #MACRO mymess 2 Removing JOB_NOT_YET_COMPLETED in $where
-	    sixdeskmess -1 "Removing JOB_NOT_YET_COMPLETED in $where"
+	    sixdeskmess 1 "Removing JOB_NOT_YET_COMPLETED in $where"
 #MACRO mymess
 	    
 	    rm -f $where/JOB_NOT_YET_COMPLETED
@@ -1156,8 +1160,7 @@ function downloadNewResults(){
 		then
 		    rm -r $where/sixtrack
 		fi
-		echo "Final state of $where"
-		ls -l $where
+		sixdeskmess 2 "Final state of $where" "ls -l $where"
 	    fi
 	fi
 	if test "$delete" = "true"
@@ -1185,7 +1188,7 @@ function downloadNewResults(){
 	    then
 		
 #MACRO mymess 1 Deleting result $ntaskid from the server
-		sixdeskmess -1 "Deleting result $ntaskid from the server"
+		sixdeskmess 1 "Deleting result $ntaskid from the server"
 #MACRO mymess
 		
 		perl ${SCRIPTDIR}/perl/confirmResultDownload.pl $ntaskid > $tmp 2>&1
@@ -1203,7 +1206,7 @@ function downloadNewResults(){
 	    then
 		
 #MACRO mymess 1 Deleting result $taskid
-		sixdeskmess -1 "Deleting result $taskid"
+		sixdeskmess 1 "Deleting result $taskid"
 #MACRO mymess
 		
 		if test "$Runnam" != ""
@@ -1212,7 +1215,7 @@ function downloadNewResults(){
 		    # and try and remove Alex .done and .zip
 		    
 #MACRO mymess 1 Deleting .done and .zip
-		    sixdeskmess -1 "Deleting .done and .zip"
+		    sixdeskmess 1 "Deleting .done and .zip"
 #MACRO mymess
 		    
 		    rm -f $sixdeskboincdir/work/${workspace}_${boincRunnam}_1_sixvf_$taskid.desc.done
@@ -1231,7 +1234,7 @@ function downloadNewResults(){
 	    then
 		
 #MACRO mymess 0 Download FAILED for $taskid : $where  !!!
-		sixdeskmess -1 "Download FAILED for $taskid : $where  !!!"
+		sixdeskmess 1 "Download FAILED for $taskid : $where  !!!"
 #MACRO mymess
 		
 		let failed+=1
@@ -1248,7 +1251,7 @@ function downloadNewResults(){
 	    let duplicated+=1
 	    
 #MACRO mymess 1 $taskid ignored (duplicate/redundant result)
-	    sixdeskmess -1 "$taskid ignored (duplicate/redundant result)"
+	    sixdeskmess 1 "$taskid ignored (duplicate/redundant result)"
 #MACRO mymess
 	    
 	elif test "$success" = "true"
@@ -1256,7 +1259,7 @@ function downloadNewResults(){
 	    let __ok+=1
 	    
 #MACRO mymess 1 $taskid downloaded successfully to $where
-	    sixdeskmess -1 "$taskid downloaded successfully to $where"
+	    sixdeskmess 1 "$taskid downloaded successfully to $where"
 #MACRO mymess
 	    
 	fi
@@ -1275,6 +1278,28 @@ function downloadNewResults(){
     return ${__lreturn}
 }
 
+function check_output_option(){
+    local __selected_output_valid
+    __selected_output_valid=false
+    
+    case ${OPTARG} in
+    ''|*[!0-2]*) __selected_output_valid=false ;;
+    *)           __selected_output_valid=true  ;;
+    esac
+
+    if ! ${__selected_output_valid}; then
+	echo "ERROR: Option -o requires the following arguments:"
+	echo "    0: only error messages and basic output [default]"
+	echo "    1: full output"
+	echo "    2: extended output for debugging"
+	exit
+    else
+	loutform=true
+	sixdesklevel_option=${OPTARG}
+    fi
+    
+}
+
 # ------------------------------------------------------------------------------
 # preliminary to any action
 # ------------------------------------------------------------------------------
@@ -1288,10 +1313,11 @@ fi
 
 lbackcomp=true
 lreconsiderTrashed=false
+loutform=false
 trashbin=/afs/cern.ch/work/b/boinc/download
 
 # get options (heading ':' to disable the verbose error handling)
-while getopts  ":hBt" opt ; do
+while getopts  ":hBto:" opt ; do
     case $opt in
 	h)
 	    how_to_use
@@ -1304,6 +1330,10 @@ while getopts  ":hBt" opt ; do
 	t)
 	    lreconsiderTrashed=true
 	    ;;
+	o)
+	    # output option
+	    check_output_option
+	    ;;	
 	:)
 	    how_to_use
 	    echo "Option -$OPTARG requires an argument."
@@ -1325,6 +1355,10 @@ OPTIND=1
 # Even if called with a Study ($1) and a Platform ($2)
 # we can now use dot_env
 source ${SCRIPTDIR}/bash/dot_env
+
+if ${loutform} ; then
+    sixdesklevel=${sixdesklevel_option}
+fi
 
 # current study
 currStudy=`basename $sixdeskstudy`
