Adding -l option to run_results, ie list number of available results
The number of results in spooldir, new and olf zip archives are given. The
actual files are not listed, though.

At the same time some code refactoring:
* main DB is updates as the my* is, i.e. with sed running only at the end
  of processing, and not for every downloaded result. This should improve
  robustness and speed of processing;
* counting number of lines/words in fort.10 no longer goes through an
  additional call to awk;
* the printout on terminal with some reference values taken from fort.10
  is triggered only if the output level is >1. Below such a threshold,
  the fields in fort.10 are not even retrieved;
* a trivial check of number of lines of DB is coded in a specific function;

diff --git a/utilities/bash/run_results b/utilities/bash/run_results
--- a/utilities/bash/run_results
+++ b/utilities/bash/run_results
@@ -28,12 +28,35 @@ function how_to_use() {
            for the moment, this sticks only to job names
    -t      reprocess old archives of results already parsed
    -n      renew kerberos token every n jobs (default: ${NrenewKerberosDef})
+   -l      only list available results
    -o      define output (preferred over the definition of sixdesklevel in sixdeskenv)
                0: only error messages and basic output 
                1: full output
                2: extended output for debugging
 
 EOF
+}
+
+function checkDBnLines(){
+    # returns lequal
+    local __lprint=$1
+    local __lcheck=$2
+    lequal=false
+    nAll=`wc -l < ${dbAll}`
+    nInc=`wc -l < ${dbInc}`
+    nCom=`wc -l < ${dbCom}`
+    let nChk=${nInc}+${nCom}
+    if ${__lcheck} ; then
+	if [ ${nAll} -ne ${nChk} ] ; then
+	    let nDiff=${nAll}-${nChk}
+	    sixdeskmess -1 "different number of entries in ${dbAll} (${nAll}) and ${dbInc} (${nInc}) plus ${dbCom} (${nCom}) - diff: ${nDiff}"
+	else
+	    sixdeskmess  1 "same number of entries in ${dbAll} (${nAll}) and ${dbInc} (${nInc}) plus ${dbCom} (${nCom})"
+	    lequal=true
+	fi
+    elif ${__lprint} ; then
+	sixdeskmess -1 "number of entries in ${dbAll}/${dbInc}/${dbCom} ${nAll}/${nInc}/${nCom}"
+    fi
 }
 
 # A new subroutine to update mydatabase......
@@ -43,6 +66,7 @@ update_cases()
   # using the new completed_this_run file (or left over from a
   # previous run_results which was killed for some reason).
   touch $sixdeskwork/completed_this_run
+  touch $sixdeskjobs/completed_tasks_this_run
 
 #MACRO mymktmp newccases $sixdeskwork
   sixdesktmpname=newccases
@@ -64,16 +88,28 @@ update_cases()
   sort --unique $newccases > $sixdeskwork/mycompleted_cases
   rm $newccases
   rm -f $sixdeskwork/sedscript.sed
-  touch $sixdeskwork/sedscript.sed
-  while read mycase
-  do
   #make a sed script
+  while read mycase ; do
     echo "/^${mycase}$/d" >> $sixdeskwork/sedscript.sed
   done < $sixdeskwork/completed_this_run
   sed -f $sixdeskwork/sedscript.sed $sixdeskwork/myincomplete_cases > $newicases
   cp $newicases $sixdeskwork/myincomplete_cases
+
+  # apply the same logics to regular main DB
+  cat $sixdeskwork/completed_cases $sixdeskwork/completed_this_run | sort -u > $sixdeskwork/completed_cases
+  sed -i -f $sixdeskwork/sedscript.sed $sixdeskwork/incomplete_cases
+  # apply the same logics to plaform DB
+  rm -f $sixdeskjobs/sedscript.sed
+  while read aline ; do
+      echo "/^${aline}$/d" >> $sixdeskjobs/sedscript.sed
+  done < $sixdeskjobs/completed_tasks_this_run
+  sed -i -f $sixdeskjobs/sedscript.sed $sixdeskjobs/incomplete_tasks
+  sed -i -f $sixdeskjobs/sedscript.sed $sixdeskjobs/completed_tasks
+  cat $sixdeskjobs/completed_tasks $sixdeskjobs/completed_tasks_this_run > $sixdeskjobs/completed_tasks
+
   rm -f $newicases
   rm -f $sixdeskwork/completed_this_run
+  rm -f $sixdeskjobs/completed_tasks_this_run
   # and make another report
 
 #MACRO mymess 1 Due to an AFS/Linux bug we maintain another database
@@ -105,6 +141,7 @@ update_cases()
   sixdeskmess -1 "Before/after this download $cases mycases, $ccases complete ($icases incomplete)"
 #MACRO mymess
 
+  sixdeskmess -1 "Present status of regular DB: `wc -l < $sixdeskjobs/tasks` cases, `wc -l < $sixdeskjobs/completed_tasks` complete (`wc -l < $sixdeskjobs/incomplete_tasks` incomplete)"
 }
 
 function getListNewResults(){
@@ -618,8 +655,8 @@ function downloadNewResults(){
 				fi
 			    fi
 			else
-			    words=`wc -w fort.10 | awk '{print ($1)}'`
-			    lines=`wc -l fort.10 | awk '{print ($1)}'`
+			    words=`wc -w < fort.10`
+			    lines=`wc -l < fort.10`
 			    nwords=`expr $sixdeskpairs \* 60`
 			    if test "$words" -ne  $nwords -o "$lines" -ne $sixdeskpairs
 			    then
@@ -637,16 +674,17 @@ function downloadNewResults(){
 				delete="true"
 				anerror="true"
 			    else 
-				line1=`head -1 fort.10`
-				local __messLine1=`echo $line1 | awk '{print ("Maxturn",$1,"Lost",$2,"Qx/Qy",$3,$4)}'`
-				local __messLine2=`echo $line1 | awk '{print (" 1st Ampx/y",$7,$8,"2nd",$26,$27)}'`
-				local __messLine3=`echo $line1 | awk '{print ("DP",$9,"Findist",$10,"Maxslope",$11,"Turns",$22,$23)}'`
-				local __messLine4=`echo $line1 | awk '{print ("CPU",$60,"seconds Version",$52)}'`
-				sixdeskmess 1 "${__messLine1}"
-				sixdeskmess 1 "${__messLine2}"
-				sixdeskmess 1 "${__messLine3}"
-				sixdeskmess 1 "${__messLine4}"
-				
+				if [ ${sixdesklevel_option} -gt 1 ] ; then
+				    line1=`head -1 fort.10`
+				    local __messLine1=`echo $line1 | awk '{print ("Maxturn",$1,"Lost",$2,"Qx/Qy",$3,$4)}'`
+				    local __messLine2=`echo $line1 | awk '{print (" 1st Ampx/y",$7,$8,"2nd",$26,$27)}'`
+				    local __messLine3=`echo $line1 | awk '{print ("DP",$9,"Findist",$10,"Maxslope",$11,"Turns",$22,$23)}'`
+				    local __messLine4=`echo $line1 | awk '{print ("CPU",$60,"seconds Version",$52)}'`
+				    sixdeskmess 1 "${__messLine1}"
+				    sixdeskmess 1 "${__messLine2}"
+				    sixdeskmess 1 "${__messLine3}"
+				    sixdeskmess 1 "${__messLine4}"
+				fi
 				gzip -f fort.10
 				ignore="false"
 				success="true"
@@ -1049,106 +1087,7 @@ function downloadNewResults(){
 	    # Now we make a file completed_this_run which we will
 	    # use to update a parallel mycompleted_cases and myincomplete_cases
 	    echo "$Runnam" >> $sixdeskwork/completed_this_run
-	    touch $sixdeskwork/DEBUG
-	    sed -i -e"/^${Runnam}$/d" $sixdeskwork/incomplete_cases
-	    if test $? -ne 0
-	    then
-		stat $sixdeskwork/incomplete_cases >> $sixdeskwork/DEBUG
-		stat $tmp >> $sixdeskwork/DEBUG
-		
-#MACRO mymess 0 AFS problem with incomplete cases!!!
-		sixdeskmess -1 "AFS problem with incomplete cases!!!"
-#MACRO mymess
-		
-		
-#MACRO mymess 0 `stat $sixdeskwork/incomplete_cases`
-		sixdeskmess -1 "`stat $sixdeskwork/incomplete_cases`"
-#MACRO mymess
-		
-		
-#MACRO mymess 0 `stat $tmp`
-		sixdeskmess -1 "`stat $tmp`"
-#MACRO mymess
-		
-		
-#MACRO myunlock $sixdeskstudy
-		sixdesklockdir=$sixdeskstudy
-		sixdeskunlock
-#MACRO myunlock
-		
-		
-#MACRO myexit 999
-		sixdeskexitparam=999
-		sixdeskexit
-#MACRO myexit
-		
-	    fi
-	    dicases=`wc -l $sixdeskwork/incomplete_cases | awk '{print ($1)}'`
-	    if test -s $sixdeskwork/completed_cases
-	    then
-		sed -i -e"/^${Runnam}$/d" $sixdeskwork/completed_cases
-		if test $? -ne 0
-		then
-		    stat $sixdeskwork/completed_cases >> $sixdeskwork/DEBUG
-		    stat $tmp >> $sixdeskwork/DEBUG
-		    
-#MACRO mymess 0 AFS problem with completed cases!!!
-		    sixdeskmess -1 "AFS problem with completed cases!!!"
-#MACRO mymess
-		    
-		    
-#MACRO mymess 0 `stat $sixdeskwork/completed_cases`
-		    sixdeskmess -1 "`stat $sixdeskwork/completed_cases`"
-#MACRO mymess
-		    
-		    
-#MACRO mymess 0 `stat $tmp`
-		    sixdeskmess -1 "`stat $tmp`"
-#MACRO mymess
-
-		    
-#MACRO myunlock $sixdeskstudy
-		    sixdesklockdir=$sixdeskstudy
-		    sixdeskunlock
-#MACRO myunlock
-		    
-		    
-#MACRO myexit 999
-		    sixdeskexitparam=999
-		    sixdeskexit
-#MACRO myexit
-		    
-		fi
-	    fi
-	    echo $Runnam >> $sixdeskwork/completed_cases
-	    dccases=`wc -l $sixdeskwork/completed_cases | awk '{print ($1)}'`
-	    tot=`expr $dicases + $dccases`
-	    allcases=`wc -l $sixdeskwork/taskids | awk '{print ($1)}'`
-	    if test "$tot" -ne "$allcases"
-	    then
-		
-#MACRO mymess 0 DEBUGZ $tot NOT= $allcases !!!
-		sixdeskmess -1 "DEBUGZ $tot NOT #MACRO mymess"
-		
-		stat $sixdeskwork/completed_cases >> $sixdeskwork/DEBUG
-		stat $sixdeskwork/incomplete_cases >> $sixdeskwork/DEBUG
-		
-#MACRO mymess 0 `stat $sixdeskwork/completed_cases`
-		sixdeskmess -1 "`stat $sixdeskwork/completed_cases`"
-#MACRO mymess
-		
-		
-#MACRO mymess 0 `stat $sixdeskwork/incomplete_cases`
-		sixdeskmess -1 "`stat $sixdeskwork/incomplete_cases`"
-#MACRO mymess
-		
-		
-#MACRO myunlock $sixdeskstudy
-		###sixdesklockdir=$sixdeskstudy
-		###sixdeskunlock
-#MACRO myunlock
-		
-	    fi
+	    echo "$Runnam ${taskid}" >> $sixdeskjobs/completed_tasks_this_run
 	    #Eric here we should now delete other redundant tasks
 	    #mess="Taskids were x$taskids""x"
 	    #taskids=`echo "$taskids" | sed -e's? '$taskid' ? ?'`
@@ -1186,24 +1125,6 @@ function downloadNewResults(){
 	if test "$delete" = "true"
 	then
 	    # success = true => delete = true
-	    if test "$unknown" = "false"
-	    then
-		
-#MACRO mylock $sixdeskjobs
-		###sixdesklockdir=$sixdeskjobs
-		###sixdesklock
-#MACRO mylock
-		
-		sed -i -e"/${Runnam} ${taskid}/d" $sixdeskjobs/incomplete_tasks
-		sed -i -e"/${Runnam} ${taskid}/d" $sixdeskjobs/completed_tasks
-		echo "${Runnam} ${taskid}" >> $sixdeskjobs/completed_tasks
-		
-#MACRO myunlock $sixdeskjobs
-		###sixdesklockdir=$sixdeskjobs
-		###sixdeskunlock
-#MACRO myunlock
-		
-	    fi
 	    if test $sixdeskplatform = "cpss"
 	    then
 		
@@ -1346,6 +1267,7 @@ lreconsiderDelete=false
 loutform=false
 downloadDir=/afs/cern.ch/work/b/boinc/download
 lunlockRunRes=false
+lProceedRunRes=true
 NrenewKerberosDef=2000
 NrenewKerberos=${NrenewKerberosDef}
 optArgCurrStudy="-s"
@@ -1354,7 +1276,7 @@ optArgCurrPlatForm=""
 unlockSetEnv=""
 
 # get options (heading ':' to disable the verbose error handling)
-while getopts  ":hBto:n:d:p:U" opt ; do
+while getopts  ":hBto:n:d:p:Ul" opt ; do
     case $opt in
 	h)
 	    how_to_use
@@ -1394,6 +1316,10 @@ while getopts  ":hBto:n:d:p:U" opt ; do
 	    # unlock currently locked folder
 	    lunlockRunRes=true
 	    unlockSetEnv="-U"
+	    ;;
+	l)
+	    # only list results
+	    lProceedRunRes=false
 	    ;;
 	:)
 	    how_to_use
@@ -1547,8 +1473,7 @@ then
 
 fi
 # Now update my database if a completed_this_run file exists froma previous run
-if test -s $sixdeskwork/completed_this_run
-then
+if [ -s $sixdeskwork/completed_this_run ] || [ -s $sixdeskjobs/completed_tasks_this_run ] ; then
 
 #MACRO mylock $sixdeskwork
   ###sixdesklockdir=$sixdeskwork
@@ -1611,16 +1536,24 @@ echo ""
 echo ""
 sixdeskmess -1 "looking for results in $sixdeskboincdir/results"
 
-# get list of new results originally from CPU resource
-# it produces:
-# - sixdesktasklist: a file with the takslist of results (eg boincXXXX)
-getListNewResults $sixdeskboincdir/results
+if ${lProceedRunRes} ; then
+    # get list of new results originally from CPU resource
+    # it produces:
+    # - sixdesktasklist: a file with the takslist of results (eg boincXXXX)
+    getListNewResults $sixdeskboincdir/results
 
-# download results and save them in track tree
-downloadNewResults $sixdeskboincdir/results $sixdesktasklist ""
-
-# update the my* DB
-update_cases
+    # download results and save them in track tree
+    downloadNewResults $sixdeskboincdir/results $sixdesktasklist ""
+    # update the my* DB
+    update_cases
+else
+    nFoundNewResults=`ls -1 $sixdeskboincdir/results/${workspace}_${LHCDesName}__\*_1_sixvf_boinc\* 2> /dev/null | wc -l `
+    if [ ${nFoundNewResults} -gt 0 ] ; then
+	sixdeskmess -1 "...found ${nFoundNewResults} fresh results from BOINC!"
+    else
+	sixdeskmess -1 "...no fresh results from BOINC!"
+    fi
+fi
 
 echo ""
 printf '=%.0s' {1..80}
@@ -1629,84 +1562,125 @@ echo ""
 
 # look into downloadDir: in case zipped files are there, then
 #    download all results there contained
-allArchives=`ls -1 ${downloadDir}/????-??-??/${workspace}_${currStudy}__*.zip 2> /dev/null`
-if ${lreconsiderDelete} ; then
-    allArchives="${allArchives} `ls -1 ${downloadDir}/*/delete/${workspace}_${currStudy}__*.zip 2> /dev/null`"
-fi
-if [ -z "${allArchives}" ] ; then
-    echo ""
-    printf '=%.0s' {1..80}
-    echo ""
-    echo ""
-    sixdeskmess -1 "No results for the time being in ${downloadDir}"
-    echo ""
-    printf '=%.0s' {1..80}
-    echo ""
-    echo ""
-else
-    for tmpArchive in ${allArchives} ; do
-	
-	tmpArchiveName=`basename ${tmpArchive}`
-	tmpArchiveDir=`dirname ${tmpArchive}`
-	tmpExtractDir=/tmp/${tmpArchiveName//.zip/}
-	
-	echo ""
-	printf '=%.0s' {1..80}
-	echo ""
-	echo ""
-	sixdeskmess -1 "You have results in ${tmpArchiveDir} archived in ${tmpArchiveName}!!"
-	sixdeskmess -1 "I will download them as well!!"
-	
-	# set trap
-	trap "rm -rf ${tmpExtractDir}" 0
-	
-	unzip ${tmpArchive} -d ${tmpExtractDir}
-	
-	# get list of new results originally from CPU resource
-	# it produces:
-	# - sixdesktasklist: a file with the takslist of results (eg boincXXXX)
-	getListNewResults ${tmpExtractDir}
-	
-	# download results and save them in track tree
-	downloadNewResults ${tmpExtractDir} $sixdesktasklist "_0"
-	
-	# update the my* DB
-	update_cases
-	
-	if [ $? -eq 0 ] ; then
-	# mv in delete only brand new results
-	    if [[ "${tmpArchive}" != *"/delete/"* ]] ; then
-	    mv ${tmpArchive} ${tmpArchiveDir}/delete/${tmpArchiveName}
-	    fi
-	fi
-	
-	rm -rf ${tmpExtractDir}
-	# reset trap
-	trap - 0
-	
-	echo ""
-	printf '=%.0s' {1..80}
-	echo ""
-	echo ""
-    
+allNewArchives=`ls -1 ${downloadDir}/????-??-??/${workspace}_${currStudy}__*.zip 2> /dev/null`
+allOldArchives=`ls -1 ${downloadDir}/*/delete/${workspace}_${currStudy}__*.zip 2> /dev/null`
+echo ""
+printf '=%.0s' {1..80}
+echo ""
+echo ""
+if [ -n "${allNewArchives}" ] ; then
+    nNewArchives=`echo "${allNewArchives}" | wc -l`
+    nNewResults=0
+    sixdeskmess -1 "Found ${nNewArchives} archives with fresh results from BOINC:"
+    for tmpArchive in ${allNewArchives} ; do
+	nResults=`zipinfo -1 ${tmpArchive} | grep '_0$' | wc -l`
+	sixdeskmess -1 "...archive ${tmpArchive} - results: ${nResults}"
+	let nNewResults+=${nResults}
     done
-fi
-    
-sixdeskmess -1 "Before this run of `basename $0`: $cases total cases, $ccases complete ($icases incomplete)"
-
-if test "$ready" -ne 0
-then
-
-#MACRO mymess 0 Of $ready Ready results, $ok were downloaded successfully, $duplicated were deleted as duplicate/redundant, and $failed failed.
-  sixdeskmess -1 "Of $ready Ready results, $ok were downloaded successfully, $duplicated were deleted as duplicate/redundant, and $failed failed."
-#MACRO mymess
-
+    sixdeskmess -1 "...for a total of ${nNewResults} fresh results from BOINC"
 else
+    sixdeskmess -1 "...no archives with fresh results from BOINC"
+fi
+echo ""
+if [ -n "${allOldArchives}" ] ; then
+    nOldArchives=`echo "${allOldArchives}" | wc -l`
+    nOldResults=0
+    sixdeskmess -1 "Found ${nOldArchives} archives with old results from BOINC:"
+    for tmpArchive in ${allOldArchives} ; do
+	nResults=`zipinfo -1 ${tmpArchive} | grep '_0$' | wc -l`
+	sixdeskmess -1 "...archive ${tmpArchive} - results: ${nResults}"
+	let nOldResults+=${nResults}
+    done
+    sixdeskmess -1 "...for a total of ${nOldResults} old results from BOINC"
+else
+    sixdeskmess -1 "...no archives with old results from BOINC"
+fi
+echo ""
+printf '=%.0s' {1..80}
+echo ""
+echo ""
 
-#MACRO mymess 0 There were no results available
-  sixdeskmess -1 "There were no results available"
-#MACRO mymess
+if ${lProceedRunRes} ; then
+    if ${lreconsiderDelete} ; then
+	allArchives="${allNewArchives} ${allOldArchives}"
+    else
+	allArchives="${allNewArchives}"
+    fi
+    if [ -z "${allArchives}" ] ; then
+        echo ""
+        printf '=%.0s' {1..80}
+        echo ""
+        echo ""
+        sixdeskmess -1 "No results from ${downloadDir} to process"
+        echo ""
+        printf '=%.0s' {1..80}
+        echo ""
+        echo ""
+    else
+    
+        for tmpArchive in ${allArchives} ; do
+    	
+    	    tmpArchiveName=`basename ${tmpArchive}`
+    	    tmpArchiveDir=`dirname ${tmpArchive}`
+    	    tmpExtractDir=/tmp/${tmpArchiveName//.zip/}
+    	
+    	    echo ""
+    	    printf '=%.0s' {1..80}
+    	    echo ""
+    	    echo ""
+    	    sixdeskmess -1 "You have results in ${tmpArchiveDir} archived in ${tmpArchiveName}!!"
+    	    sixdeskmess -1 "I will download them as well!!"
+    	
+            # set trap
+    	    trap "rm -rf ${tmpExtractDir}" 0
+    	
+    	    unzip ${tmpArchive} -d ${tmpExtractDir}
+    	
+            # get list of new results originally from CPU resource
+    	    # it produces:
+    	    # - sixdesktasklist: a file with the takslist of results (eg boincXXXX)
+    	    getListNewResults ${tmpExtractDir}
+	
+	    # download results and save them in track tree
+	    downloadNewResults ${tmpExtractDir} $sixdesktasklist "_0"
+   	    # update the my* DB
+	    update_cases
+	
+	    if [ $? -eq 0 ] ; then
+	        # mv in delete only brand new results
+		if [[ "${tmpArchive}" != *"/delete/"* ]] ; then
+		    mv ${tmpArchive} ${tmpArchiveDir}/delete/${tmpArchiveName}
+		fi
+	    fi
 
+	    rm -rf ${tmpExtractDir}
+ 	    # reset trap
+	    trap - 0
+	
+	    echo ""
+	    printf '=%.0s' {1..80}
+	    echo ""
+	    echo ""
+	    
+	done
+    fi
+    
+    sixdeskmess -1 "Before this run of `basename $0`: $cases total cases, $ccases complete ($icases incomplete)"
+
+    if test "$ready" -ne 0
+    then
+
+        #MACRO mymess 0 Of $ready Ready results, $ok were downloaded successfully, $duplicated were deleted as duplicate/redundant, and $failed failed.
+	sixdeskmess -1 "Of $ready Ready results, $ok were downloaded successfully, $duplicated were deleted as duplicate/redundant, and $failed failed."
+        #MACRO mymess
+
+    else
+
+        #MACRO mymess 0 There were no results available
+	sixdeskmess -1 "There were no results available"
+        #MACRO mymess
+	
+    fi
 fi
 
 #MACRO myunlock $sixdeskstudy
@@ -1738,11 +1712,13 @@ then
 fi
 
 #MACRO mymess 0 After  this download $cases cases, $ccases complete ($icases incomplete)
-sixdeskmess -1 "After  this download $cases cases, $ccases complete ($icases incomplete)"
+sixdeskmess -1 "Present status of DB: $cases cases, $ccases complete ($icases incomplete)"
 #MACRO mymess
 
 # update the my* DB
-update_cases
+if [ -s $sixdeskwork/completed_this_run ] || [ -s $sixdeskjobs/completed_tasks_this_run ] ; then
+    update_cases
+fi
 rm -f $tmp
 
 #MACRO myunlock $sixdeskwork
